blank_issues_enabled: false
contact_links:
  - name: Report a Bug
    url: https://github.com/ArioMoniri/NeoPaste/issues/new?assignees=&labels=bug&template=bug_report.md&title=Bug%3A+
    about: Use this template to report a bug.
  - name: Feature Request
    url: https://github.com/ArioMoniri/NeoPaste/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Feature%3A+
    about: Use this template to request a new feature or enhancement.
